- name: verfiy distribution
  fail: msg="unsupported distribution"
  when: "ansible_distribution != 'Ubuntu'"

- name: verify architecture
  fail: msg="unsupported architecture"
  when: "ansible_architecture != 'x86_64'"

- name: add repository key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "0EBFCD88"

- name: add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

- name: install docker
  apt:
    name: docker-ce
    install_recommends: yes

- name: enable service
  systemd:
    name: docker
    enabled: yes
    state: started
